version: 2

aliases:
  - &restore_node_modules
    restore_cache:
      keys:
        - yarn-packages-{{ .Branch }}-{{ checksum "yarn.lock" }}
        - yarn-packages-{{ .Branch }}
        - yarn-packages-master
        - yarn-packages-
  - &save_node_modules
    save_cache:
      key: yarn-packages-{{ .Branch }}-{{ checksum "yarn.lock" }}
      paths:
        - node_modules

jobs:
  build:
    working_directory: ~/kaave/github-page-src
    docker:
      - image: 'circleci/node:10'
    branches:
      only:
        - master
    steps:
      - checkout
      - run:
          name: git setup
          command: |
            git config --global user.name "CircleCI"
            git config --global user.email "circleci@example.com"
      - run:
          name: yarn install
          command: yarn install
      # - *save_node_modules
      - run:
          name: create .env
          command: cp .env.example .env
      - run:
          name: build
          command: yarn generate
      - run:
          name: commit
          working_directory: ~/kaave/github-page-src/dist
          command: |
            git init
            git remote add origin git@github.com:kaave/kaave.github.io.git
      - run:
          name: Deploy new version
          working_directory: ~/kaave/github-page-src/dist
          command: |
            git add .
            git commit -m "[ci skip] publish"
            git push origin master -f
