query content($orderBy: EntryOrderByInput) {
  entries(orderBy: $orderBy) {
    status
    id
    publish
    subject
    entry
    thumbnail {
      url
      mimeType
      fileName
      width
      height
      size
    }
  }
}
